### ISSUE TITLE
Sync tabs in split view

### ISSUE THREAD

**Issue by skttl** [skttl/umbraco-matryoshka#10]
An interesting idea popped up on our.
https://our.umbraco.com/forum/umbraco-8/93641-discussion-about-tabs#comment-317850

Syncing the tabs when working in split views. I like the idea, but should probably be togglable.

If anyone wants to give it a go, I've marked it up for grabs :)

**Comment by FransdeJong** [comment]
I've started working on this. I'll try to have a PR by the end of the weekend.

**Comment by FransdeJong** [comment]
I created the functionality including the syncing of the scrollto functionality
PR can be found here: https://github.com/skttl/umbraco-matryoshka/pull/34
