### ISSUE TITLE
First group seperator doesn't appear in tab drop-down

### ISSUE THREAD

**Issue by stefankip** [skttl/umbraco-matryoshka#28]
I have a document type groep, with 2 matryoshka group seperators (single datatype).
The first seperator is the first property of the group and isn't displayed in the tab drop-down.
The second seperator is shown in the drop-down.

When I move the first property to be the second property, the group is shown in the tab drop-down.

**Comment by skttl** [comment]
Hi @stefankip 

This is originally intended behaviour, as the first group was supposed to be kind of a headline for the tab. But after adding the config for selecting whether or not the group should be in the dropdown, it does indeed make sense to put it there anyway :)

It's an easy fix, and I'll get it in the next release :)
