### ISSUE TITLE
Tabs are not working correctly in smaller screens

### ISSUE THREAD

**Issue by FransdeJong** [skttl/umbraco-matryoshka#35]
While working on issue #10 I found out that the functionality to hide tabs on smaller screens is not working correctly.
The 3 dots apear to soon on the new line. Something must be off with the width calculation.

![matryoshka 1](https://user-images.githubusercontent.com/29602162/95677257-8d79d700-0bc4-11eb-86b2-02109c370b14.png)
![matryoshka 2](https://user-images.githubusercontent.com/29602162/95677259-8e126d80-0bc4-11eb-8560-e36da77fe437.png)

**Comment by FransdeJong** [comment]
@skttl 
I've been looking at the code and I don't understand the reasoning behind getting the container. ( https://github.com/skttl/umbraco-matryoshka/blob/master/src/Our.Umbraco.Matryoshka/App_Plugins/Our.Umbraco.Matryoshka/directives/matryoshka-tabbed-content.directive.js#L18 )

We could just do the calculations on the $element itself or am I missing something?

I can fix the issue but don't want to mess your code up when I don't understand the reasoning behind the code ;-)

**Comment by skttl** [comment]
You are right - that would be much better :)

I read your comment like you almost have a PR ready?

**Comment by FransdeJong** [comment]
I've identified the issue so I can have a PR ready by tomorrow if you want

**Comment by skttl** [comment]
Would be sweet - reviewing your other PR right now, if my flaky cabin wifi keeps working :) #codecabin20ftw :)

**Comment by FransdeJong** [comment]
Will do. I'll report back when it's ready

**Comment by FransdeJong** [comment]
Fixed in https://github.com/skttl/umbraco-matryoshka/pull/37
