### ISSUE TITLE
Tabs in DTGE looks strange

### ISSUE THREAD

**Issue by enkelmedia** [skttl/umbraco-matryoshka#41]
Not sure if this is an issue in Matryoshka or Doc Type Grid Editor but after installing Matryoshka tabs inside a editor-window looks strange, no "width" is applied to the control-header.

![without](https://user-images.githubusercontent.com/1782524/97187463-bdb79d00-17a2-11eb-859b-1639ac14c0d1.PNG)

After looking in the source for umbraco it turns out that they've added some selector to the css for the width, so adding the class "form-horizontal" to the ng-form name="tabbedContentForm" solved this for me:

![with](https://user-images.githubusercontent.com/1782524/97187478-c1e3ba80-17a2-11eb-86ce-9820aa983bb8.PNG)

**Comment by enkelmedia** [comment]
Let me know if you would like a PR

**Comment by skttl** [comment]
Would love a PR, can you check if it's DTGE or Matryoshka that needs fixing?

**Comment by enkelmedia** [comment]
After looking at this and performing a temporary fix for one of our clients I would say that this is a class that should be added to the "ng-form" with name "tabbedContentForm" which is a form in Matryoshka.

Just adding class "form-horizontal" makes this look good again.

**Comment by skttl** [comment]
Thanks, then it must be in Matryoshka 👍 

I guess the problem might exist in DTGE too, I'll check.

**Comment by lars-erik** [comment]
Here's a curveball... We just _got_ this problem when upgrading to 0.6.0 of Matryoshka with DTGE 1.2.5 installed.  
Removing form-horizontal fixes the layout problem. 🤔

**Comment by skttl** [comment]
Eek, which Umbraco Version?

**Comment by skttl** [comment]
Okay, I tried a few versions now. Seems like something changes in Umbraco 8.6, where form-horizontal is not needed anymore.

So I added some code, that checks for version before adding the form-horizontal class in b17d97c99389aa9c4afdcc674a35640310243345
