### ISSUE TITLE
Change of Tabs in "editor"-window changes tab on Content

### ISSUE THREAD

**Issue by enkelmedia** [skttl/umbraco-matryoshka#42]
Seems like this is a quite new issue, it not present in the current release v0.5.0 but when running the latest stuff from master it looks like this:

![m - DTGE issue](https://user-images.githubusercontent.com/1782524/97277818-3f5a0a00-1839-11eb-89a7-fc4ccc84ce49.gif)

In other words changing the tab in a "editor window" will change the tab on the underlaying node as well.

Some more info
* This examples is tabs in a "Doc Type Grid Editor"
* This does not apply when using "infinite editing" (ie opening picked node från the page)

**Comment by skttl** [comment]
Thanks for reporting this.

Related PR #36

**Comment by skttl** [comment]
Fixed in 9dabb85d4802a0e15181164dddd21d59b87978ba
