### ISSUE TITLE
Separator: Closed on load is open 

### ISSUE THREAD

**Issue by ault** [skttl/umbraco-matryoshka#48]
Umbraco 8.9.1, Matryoshka 07.0

I have 4 instances of the same separator in use on the same component data-type...

It is set as an anchor, and "Collapsible, closed on load".

When in use, the first and third separators come in as expected (i.e. closed on open). However, the second and fourth are open.  Nothing appears in the devtools console.  

Is this a known issue?

**Comment by skttl** [comment]
I didn't know it :)

**Comment by ault** [comment]
My ng is not very hot, but I'm wondering if the bug lives in this:

`        $scope.toggleCollapse = function() {
            $timeout(function() {
                separator.toggleClass("our-matryoshka-group-separator--collapsed");
                separator.nextUntil(".our-matryoshka-group-separator-container").toggleClass("our-matryoshka-group-separator--collapsed");
            });
        }
`

**Comment by ault** [comment]
With help from @HarryGordon , by adding a bit of time to timeout.toggleCollapse function, *it works* (note the 1ms). 

Not sure what the next steps would be.


```
$scope.toggleCollapse = function() {
            $timeout(function() {
                separator.toggleClass("our-matryoshka-group-separator--collapsed");
                separator.nextUntil(".our-matryoshka-group-separator-container").toggleClass("our-matryoshka-group-separator--collapsed");
            },1);
        }
```

**Comment by skttl** [comment]
I added the timeout, and it works here too :) b27567b37946ec5f45f26de09b632b37e752f00c
