### ISSUE TITLE
Umbraco 9 compatibility

### ISSUE THREAD

**Issue by chris-evansnz** [skttl/umbraco-matryoshka#56]
Just wondering if anyone has successfully used matryoshka in the Umbraco 9 beta-001 release?

I seemed to get it working by copying the App_Plugins files into wwwroot but it mysteriously stopped working a day later.  Installing via the nuget package didn't work either (wishful thinking but worth a try)

Is there a plan for a v9 version; and is there any best-practice way to get App_Plugins based directives etc to work in asp.net core / v9?

**Comment by skttl** [comment]
When it stopped a day later, did the files still exist in the App_Plugins folder? Sounds more like a bug in Umbraco, or your setup if the files dissapeared.

There is currently no plans for v9, as I expect cores own tabs functionality to be ready soon.

**Comment by chris-evansnz** [comment]
No, the files were still there, it just doesn't show the tabs. Not sure why?

**Comment by bielu** [comment]
@skttl based on that https://github.com/umbraco/Umbraco-CMS/issues/9442, I somehow dont believe tabs will actually return to core as that is already 8 months without update of ticket about tabs, so lets be honest it might not happen. :)

**Comment by skttl** [comment]
@bielu it is happening https://github.com/umbraco/Umbraco-CMS/tree/v8/prototype%2Fdoctype-tabs

**Comment by skttl** [comment]
Regarding this issue, I'm pretty sure it's a bug in the beta. If the files is there, theres nothing I can do...

**Comment by markadrake** [comment]
After running `dotnet add package Our.Umbraco.Matryoshka` I can confirm that the appropriate files **are not added** to my project.

![image](https://user-images.githubusercontent.com/713355/121797103-1d58a080-cbec-11eb-88ca-3ab93896f67b.png)

So I downloaded the latest release (0.7.0), unzipped the files, and placed them correctly under `App_Plugins`.

![image](https://user-images.githubusercontent.com/713355/121797123-47aa5e00-cbec-11eb-99f6-240b9ae891a6.png)

I can confirm that the tabs are in place and in working order.

![image](https://user-images.githubusercontent.com/713355/121797150-73c5df00-cbec-11eb-9e79-3406d7938eca.png)

**Comment by skttl** [comment]
Yes, I guess I need to create a nuget package with build targets for copying the files into the site for v9.

I'll see if I can find out if HQ are getting their tabs implementation done before v9, before I do it though.

**Comment by skttl** [comment]
With the current plans for adding tabs back into the backoffice, the roadmap for Matryoshka is now:

- Make the native tabs work with Matryoshka for 8.x
- Create a new package, responsible for migrating Matryoshka Tabs and Matryoshka Group Separators to native tabs and groups - this is going to be v8 only, so you need to run the migration in v8 before upgrading to v9.
- No support for v9
